"""Build the target-domain (sketch/clipart) manifest from DomainNet.

Expects DomainNet's `sketch/` and `clipart/` subdirectories already
downloaded (http://ai.bu.edu/M3SDA/) with the standard
`<domain>/<class_name>/<image>.jpg` layout. Captions are generated by
template rather than scraped, since DomainNet ships class labels, not
free-text captions — this keeps the caption *style* consistent within the
target domain, which is realistic (a retrieval system's target-domain
queries are often templated/short, unlike richly-described photo captions).

Output: data/target/images/*.jpg + data/target/splits.json
"""
from __future__ import annotations

import argparse
import json
import os
import random
import shutil

DOMAIN_TEMPLATES = {
    "sketch": "a sketch of a {cls}",
    "clipart": "a clipart image of a {cls}",
}

# Restrict to classes that plausibly overlap with common COCO-style source
# vocabulary, so the drop we measure is about domain, not novel concepts.
COCO_OVERLAP_CLASSES = {
    "airplane", "bicycle", "bird", "boat", "bus", "car", "cat", "chair",
    "clock", "dog", "elephant", "horse", "laptop", "motorcycle", "person",
    "pizza", "sheep", "table", "train", "truck", "umbrella", "zebra",
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--domainnet_root", required=True, help="Path to extracted DomainNet root")
    parser.add_argument("--domains", nargs="+", default=["sketch", "clipart"])
    parser.add_argument("--out_dir", default="data/target")
    parser.add_argument("--n_images", type=int, default=1500)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)
    images_out = os.path.join(args.out_dir, "images")
    os.makedirs(images_out, exist_ok=True)

    records = []
    for domain in args.domains:
        domain_root = os.path.join(args.domainnet_root, domain)
        classes = [c for c in os.listdir(domain_root) if c in COCO_OVERLAP_CLASSES]
        for cls in classes:
            cls_dir = os.path.join(domain_root, cls)
            files = os.listdir(cls_dir)
            random.shuffle(files)
            per_class_cap = max(1, args.n_images // (len(classes) * len(args.domains)))
            for fname in files[:per_class_cap]:
                src_path = os.path.join(cls_dir, fname)
                dst_rel = os.path.join("images", domain, cls, fname)
                dst_path = os.path.join(args.out_dir, dst_rel)
                os.makedirs(os.path.dirname(dst_path), exist_ok=True)
                if not os.path.exists(dst_path):
                    shutil.copy(src_path, dst_path)

                caption = DOMAIN_TEMPLATES[domain].format(cls=cls.replace("_", " "))
                records.append({"image": dst_rel, "caption": caption, "label": cls})

    random.shuffle(records)
    n = len(records)
    train_end, val_end = int(n * 0.3), int(n * 0.4)  # deliberately small train split
    splits = {
        "train": records[:train_end],
        "val": records[train_end:val_end],
        "test": records[val_end:],
    }

    with open(os.path.join(args.out_dir, "splits.json"), "w") as f:
        json.dump(splits, f)

    print(f"Wrote {n} target records -> {args.out_dir}/splits.json")
    for split, recs in splits.items():
        print(f"  {split}: {len(recs)}")


if __name__ == "__main__":
    main()
